name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        run: git fetch --prune --unshallow
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - run: go vet ./...
    - run: go test ./...

    # Only store binaries to Github Releases on tag.
    - uses: goreleaser/goreleaser-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
